import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AlertCircle, CheckCircle2, FileText, Download } from "lucide-react";

interface VisualizationPanelProps {
  originalImage: string | null;
  heatmapImage: string | null;
  result: "Normal" | "Anomaly";
  confidence: number;
}

const VisualizationPanel = ({ originalImage, heatmapImage, result, confidence }: VisualizationPanelProps) => {
  if (!originalImage || !heatmapImage) {
    return null;
  }

  const isAnomaly = result === "Anomaly";

  const handleDownloadReport = () => {
    // Create a comprehensive report
    const reportContent = `
MEDTECH INNOVATION - MEDICAL IMAGING ANALYSIS REPORT
======================================================

Analysis Date: ${new Date().toLocaleString()}
Result: ${result}
Confidence Level: ${confidence}%

CLINICAL INTERPRETATION:
${isAnomaly 
  ? `The analysis has detected anomalous patterns in the medical image with ${confidence}% confidence level.
The highlighted regions in the heatmap indicate areas where tissue characteristics deviate from normal baseline parameters.

KEY OBSERVATIONS:
- Detected irregularities in tissue density or structural patterns
- Anomalous regions show statistical deviation from normal tissue signatures
- Machine learning model confidence: ${confidence}%
- Heatmap intensity correlates with anomaly severity probability

RECOMMENDATION:
Further clinical evaluation is recommended. Correlate these findings with patient history, symptoms, and consider additional diagnostic imaging or laboratory tests as appropriate. This AI-assisted analysis should be used as a supplementary tool to support clinical decision-making.`
  : `The analysis indicates normal tissue patterns with ${confidence}% confidence level.
No significant anomalies or deviations from baseline parameters were detected in this medical image.

KEY OBSERVATIONS:
- Tissue density and structural patterns within normal ranges
- No statistical deviations from healthy tissue signatures detected
- Machine learning model confidence: ${confidence}%
- Analysis confirms absence of concerning features

RECOMMENDATION:
Continue routine monitoring as per standard protocols. While this analysis suggests normal findings, always correlate with complete patient clinical presentation and consider follow-up imaging based on clinical guidelines.`}

DISCLAIMER:
This AI-assisted analysis is designed to support clinical decision-making and should not replace professional medical judgment. Always consider complete patient history, physical examination, and additional diagnostic tests when making clinical decisions.

Generated by MedTech Innovation - Detect, Diagnose, and Defend
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medtech_report_${new Date().getTime()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Detailed Analysis Card */}
      <Card className="p-6">
        <div className="flex items-center gap-3 mb-6">
          <FileText className="h-6 w-6 text-primary" />
          <h2 className="text-2xl font-semibold text-foreground">Detailed Analysis & Interpretation</h2>
        </div>
        
        {/* Side by Side Images */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div className="space-y-3">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
              Original Medical Image
            </h3>
            <div className="rounded-lg overflow-hidden border-2 border-border bg-muted/30">
              <img
                src={originalImage}
                alt="Original medical scan"
                className="w-full h-auto"
              />
            </div>
            <p className="text-sm text-muted-foreground">
              The original medical imaging scan uploaded for analysis. This represents the raw data captured during the imaging procedure.
            </p>
          </div>

          <div className="space-y-3">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
              {isAnomaly ? "Anomaly Detection Heatmap" : "Normal Pattern Analysis"}
            </h3>
            <div className="rounded-lg overflow-hidden border-2 border-border bg-muted/30">
              <img
                src={heatmapImage}
                alt="Analysis visualization"
                className="w-full h-auto"
              />
            </div>
            <p className="text-sm text-muted-foreground">
              {isAnomaly 
                ? "Heatmap visualization highlighting detected anomalies. Warmer colors (red/yellow) indicate higher probability of abnormality."
                : "Analysis confirms normal tissue patterns with no significant deviations from baseline parameters."}
            </p>
          </div>
        </div>

        {/* Clinical Interpretation */}
        <div className="bg-muted/50 rounded-lg p-5 space-y-4">
          <div className="flex items-center gap-2 mb-3">
            {isAnomaly ? (
              <AlertCircle className="h-5 w-5 text-destructive" />
            ) : (
              <CheckCircle2 className="h-5 w-5 text-green-600" />
            )}
            <h3 className="text-lg font-semibold text-foreground">Clinical Interpretation</h3>
            <Badge variant={isAnomaly ? "destructive" : "default"}>
              {result} - {confidence}% Confidence
            </Badge>
          </div>

          <div className="space-y-3 text-sm text-foreground/90">
            {isAnomaly ? (
              <>
                <p className="leading-relaxed">
                  <strong>Finding:</strong> The analysis has detected anomalous patterns in the medical image with {confidence}% confidence level. 
                  The highlighted regions in the heatmap indicate areas where tissue characteristics deviate from normal baseline parameters.
                </p>
                <p className="leading-relaxed">
                  <strong>Key Observations:</strong>
                </p>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>Detected irregularities in tissue density or structural patterns</li>
                  <li>Anomalous regions show statistical deviation from normal tissue signatures</li>
                  <li>Machine learning model confidence: {confidence}%</li>
                  <li>Heatmap intensity correlates with anomaly severity probability</li>
                </ul>
                <p className="leading-relaxed">
                  <strong>Recommendation:</strong> Further clinical evaluation is recommended. Correlate these findings with patient history, 
                  symptoms, and consider additional diagnostic imaging or laboratory tests as appropriate. This AI-assisted analysis should 
                  be used as a supplementary tool to support clinical decision-making.
                </p>
              </>
            ) : (
              <>
                <p className="leading-relaxed">
                  <strong>Finding:</strong> The analysis indicates normal tissue patterns with {confidence}% confidence level. 
                  No significant anomalies or deviations from baseline parameters were detected in this medical image.
                </p>
                <p className="leading-relaxed">
                  <strong>Key Observations:</strong>
                </p>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>Tissue density and structural patterns within normal ranges</li>
                  <li>No statistical deviations from healthy tissue signatures detected</li>
                  <li>Machine learning model confidence: {confidence}%</li>
                  <li>Analysis confirms absence of concerning features</li>
                </ul>
                <p className="leading-relaxed">
                  <strong>Recommendation:</strong> Continue routine monitoring as per standard protocols. While this analysis suggests normal 
                  findings, always correlate with complete patient clinical presentation and consider follow-up imaging based on clinical guidelines.
                </p>
              </>
            )}
          </div>
        </div>
      </Card>

      {/* Report Summary Card */}
      <Card className="p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-xl font-semibold text-foreground">Analysis Report Summary</h3>
          <Button onClick={handleDownloadReport} className="gap-2">
            <Download className="h-4 w-4" />
            Download Report
          </Button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-muted/30 rounded-lg p-4">
            <p className="text-sm text-muted-foreground mb-1">Analysis Date</p>
            <p className="text-lg font-semibold text-foreground">{new Date().toLocaleDateString()}</p>
          </div>
          <div className="bg-muted/30 rounded-lg p-4">
            <p className="text-sm text-muted-foreground mb-1">Result Classification</p>
            <Badge variant={isAnomaly ? "destructive" : "default"} className="text-base">
              {result}
            </Badge>
          </div>
          <div className="bg-muted/30 rounded-lg p-4">
            <p className="text-sm text-muted-foreground mb-1">Confidence Score</p>
            <p className="text-lg font-semibold text-foreground">{confidence}%</p>
          </div>
        </div>
        
        <div className="mt-4 p-4 bg-primary/5 border border-primary/20 rounded-lg">
          <p className="text-xs text-muted-foreground">
            <strong>Disclaimer:</strong> This AI-assisted analysis is designed to support clinical decision-making and should not replace 
            professional medical judgment. Always consider complete patient history, physical examination, and additional diagnostic tests 
            when making clinical decisions. Consult with appropriate specialists for definitive diagnosis and treatment planning.
          </p>
        </div>
      </Card>
    </div>
  );
};

export default VisualizationPanel;
